name = "Grok"
uuid = "741f94ce-7c44-4664-a236-7dbfa09f3eda"
version = "0.1.0"
authors = ["rumor-thrower <87070008+rumor-thrower@users.noreply.github.com>"]

[deps]
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"

[compat]
MLDatasets = "0.7.20"
